# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.6
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: vince.alvare@gmail.com
author_name: Vince Alvaré
cloud_provider: netlify
preset_name: production
project_name: algokit-2

